# Generated by Django 5.0.3 on 2026-04-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0002_opinionreport'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='opinionreport',
            new_name='debates_opi_resolve_d2dc89_idx',
            old_name='debates_opi_resolve_a24531_idx',
        ),
    ]
